### ISSUE TITLE
yabridge on wine 5.0

### ISSUE THREAD

**Issue by anagram3k** [robbert-vdh/yabridge#23]
I am trying to make yabridge work on wine 5.0 and having this error message:
```
0023:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
002c:err:module:__wine_process_init failed to load L"Z:\\home\\luis\\.local\\share\\yabridge\\yabridge-host.exe.so", error c000012f
```
According to the troubleshooting guide I need to upgrade my wine installation to a newer version, but this is the latest stable version of wine. 

Do I need to use the latest development version?
If the answer is yes, It is possible to compile yabridge against wine 5.0?

**System information**
- Operating system: Ubuntu Studio 20.04
- Wine version: wine-5.0 (Ubuntu 5.0-3ubuntu1)
- Installation method: symlinks
- yabridge version: 1.2.1

**Comment by robbert-vdh** [comment]
Hi! Wine is currently at version 5.11. It's technically called a 'development release' because they're releasing them on a two week schedule, but in general there's no reason to not run the latest version of Wine Staging unless you you're facing specific problems (as a notable example, the latest versions temporarily don't support esync anymore which could be a deal breaker for playing games). The problem here is that Ubuntu just does not update their Wine packages, hence why WineHQ provides their own repositories for Ubuntu.

So to get back to your question, it is 100% possible to compile yabridge to work with older versions of Wine. This can be a bit of a struggle on older Ubuntu 18.04 based distros, but Ubuntu 20.04 ships with the right versions of GCC and Boost in its repositories so you should be fine. If you do decide to try and compile yabridge for yourself, then aside from the instructions in the readme you could also take a look at the [Docker image](https://github.com/robbert-vdh/docker-yabridge/blob/master/focal/Dockerfile) and [CI job](https://github.com/robbert-vdh/yabridge/blob/master/.github/workflows/build.yml#L69) used to build yabridge on Ubuntu 20.04. You can of course ignore the parts of the Dockerfile that install the current version of Wine Staging and the part that compiles Boost from scratch (Ubuntu 20.04 comes with Boost 1.71 which is perfectly fine, I just wanted to ensure that all builds used the same version for peace of mind).

**Comment by anagram3k** [comment]
Thanks for the explanation!
