### ISSUE TITLE
yabridge 5.1.1 doesn't compile with gcc-10

### ISSUE THREAD

**Issue by gitterdude** [robbert-vdh/yabridge#379]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

README.md says 

## Building
To compile yabridge, you'll need [Meson](https://mesonbuild.com/index.html) and
the following dependencies:
- GCC 10+

but when I tried with gcc-10.5.0 in Ubuntu 20.04 I got 

In file included from /usr/local/include/windef.h:262,
                 from /usr/local/include/windows.h:38,
                 from ../src/wine-host/bridges/../editor.h:23,
                 from ../src/wine-host/bridges/vst3.h:29,
                 from ../src/wine-host/bridges/vst3.cpp:17:
/usr/local/include/propsys.h:4074:1: error: expected unqualified-id before string constant
 4074 | PSSTDAPI PSCreateMemoryPropertyStore(REFIID,void **);
 
 It works with gcc-11.4.0 so the README should probably be updated 

### What did you expect to happen?

Compile to succeed with gcc-10 - as per the README

### What actually happened?

It failed

### Operating system

Ubuntu-20.04

### How did you install yabridge?

Source code

### yabridge version

5.1.1

### yabridgectl version

5.1.1

### Wine version

wine-9.21 (Staging)

### Plugin

none

### Plugin type

both VST2 and VST3

### Plugin architecture

both 64-bit and 32-bit

### Host

none

**Comment by F33RNI** [comment]
Same with wine-staging 10.2-1, gcc 14.2.1

**Comment by shmox75** [comment]
same here
