### ISSUE TITLE
Crash with Bitwig 3.3 beta 4 when showing the GUI

### ISSUE THREAD

**Issue by abique** [robbert-vdh/yabridge#54]
Hi,

In the latest beta we changed a few things in our plugin hosting:
- we dlopen using RTLD_DEEPBIND
- we hide symbols from third party libraries that we statically link (x11, xcb, ...)

During my tests I found that if I start the audio engine from the terminal the plugin work.
But if I let BitwigStudio start the engine it does not work.

gdb told me that it crashes due to uncaught exception from the plugin (yabridge 2.0.2):

```
#0  0x00007f467480e615 in raise () from /usr/lib/libc.so.6
#1  0x00007f46747f7862 in abort () from /usr/lib/libc.so.6
#2  0x00007f46210f586a in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f4621101d9a in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007f4621101e07 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007f46211020ae in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7f462138ba08 <typeinfo for boost::wrapexcept<boost::system::system_error>>, 
    dest=0x7f4621333af0 <boost::wrapexcept<boost::system::system_error>::~wrapexcept()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007f4621308903 in void boost::throw_exception<boost::system::system_error>(boost::system::system_error const&) () from /home/abique/.wine/drive_c/VST/FabFilter/FabFilter Pro-Q 3.so
#7  0x00007f4621337fdf in boost::asio::detail::do_throw_error(boost::system::error_code const&, char const*) () from /home/abique/.wine/drive_c/VST/FabFilter/FabFilter Pro-Q 3.so
#8  0x00007f462134584a in unsigned long boost::asio::read<boost::asio::basic_stream_socket<boost::asio::local::stream_protocol, boost::asio::executor>, boost::asio::mutable_buffers_1>(boost::asio::basic_stream_socket<boost::asio::local::stream_protocol, boost::asio::executor>&, boost::asio::mutable_buffers_1 const&, std::enable_if<boost::asio::is_mutable_buffer_sequence<boost::asio::mutable_buffers_1>::value, void>::type*) [clone .constprop.0] () from /home/abique/.wine/drive_c/VST/FabFilter/FabFilter Pro-Q 3.so
#9  0x00007f462135c63d in EventResult read_object<EventResult, boost::asio::basic_stream_socket<boost::asio::local::stream_protocol, boost::asio::executor> >(boost::asio::basic_stream_socket<boost::asio::local::stream_protocol, boost::asio::executor>&) () from /home/abique/.wine/drive_c/VST/FabFilter/FabFilter Pro-Q 3.so
#10 0x00007f4621349e01 in long EventHandler<std::jthread>::send_event<DispatchDataConverter>(DispatchDataConverter&, std::optional<std::pair<Logger&, bool> >, int, int, long, void*, float) [clone .isra.0] () from /home/abique/.wine/drive_c/VST/FabFilter/FabFilter Pro-Q 3.so
#11 0x00007f462134a20b in PluginBridge::dispatch(AEffect*, int, int, long, void*, float) () from /home/abique/.wine/drive_c/VST/FabFilter/FabFilter Pro-Q 3.so
#12 0x0000563f8f724551 in openGUI () at ../../float/pluginhost/lib/src/main/cpp/PluginInstance.cpp:1579
```

Regarding your bug report to Bitwig, why do you manipulate environ directly? Why not use secure_getenv() instead of environ?

Also it is not clear to me where you get the environ problem, is it in the plugin hosted by the audio engine or your own wine plugin host?

Regards,
Alex

**Comment by abique** [comment]
I forgot to mention that it prints on the log file `~/.BitwigStudio/log/engine.log`:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  read: End of file
```

**Comment by robbert-vdh** [comment]
Hi Alex,

We're using [`boost::this_process::environment()`](https://www.boost.org/doc/libs/1_72_0/doc/html/process/reference.html#boost.this_process.environment)/[`boost::process::native_environment`](https://www.boost.org/doc/libs/1_72_0/doc/html/process/reference.html#boost.process.native_environment) both for reading the current environment as well as to be able to launch our child process with a modified environment (which after Boost.Process does all of its magic would correspond to the `envp` parameter in `execve(2)`). On POSIX compliant platforms this is implemented as a wrapper around `environ`/`__environ`. The other place I can think of where it's used semi-regularly is JUCE's [document chooser](https://github.com/juce-framework/JUCE/blob/55df0897d104c9a20a1363c748389d821a7cea1f/modules/juce_core/native/juce_linux_Files.cpp#L221).

Also not related to yabridge bit something that may also be related to this issue, is Vital not working with Bitwig Studio 3.3 beta 4. I'm not sure if you guys have already received a report for this, but in case you have not, both the VST2 and the VST3 versions of Vital now crash as soon as the GUI refreshes (either on its own after you open it for the VST2 version or when you move your mouse over it for the VST3 version). When the plugin crashes, these X11 errors are printed to `~/.BitwigStudio/logs/engine.log`:

```
[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
BitwigPluginHost64: xcb_io.c:580: _XReply: Assertion `!xcb_xlib_extra_reply_data_left' failed.
X Error of failed request:  BadImplementation (server does not implement operation)
  Major opcode of failed request:  20 (X_GetProperty)
  Serial number of failed request:  149
  Current serial number in output stream:  150
```

And this is the GDB backtrace:

<details>

<summary>backtrace</summary>

```shell
─── Output/messages ──────────────────────────────────────────

Thread 4 "Pool" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fc235568640 (LWP 14910)]
0x00007fc23fa0f615 in raise () from /usr/lib/libc.so.6
─── History ─────────────────────────────────────────────────
─── Breakpoints ─────────────────────────────────────────────
─── Expressions ─────────────────────────────────────────────
─── Source ──────────────────────────────────────────────────
─────────────────────────────────────────────────────────────
>>> bt
#0  0x00007fc23fa0f615 in raise () at /usr/lib/libc.so.6
#1  0x00007fc23f9f8862 in abort () at /usr/lib/libc.so.6
#2  0x00007fc23f9f8747 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007fc23fa07bf6 in  () at /usr/lib/libc.so.6
#4  0x00007fc23714e8eb in _XReply () at /usr/lib/libX11.so.6
#5  0x00007fc236b791d2 in  () at /usr/lib/libGLX_nvidia.so.0
#6  0x00007fc236b24405 in  () at /usr/lib/libGLX_nvidia.so.0
#7  0x00007fc236b24558 in  () at /usr/lib/libGLX_nvidia.so.0
#8  0x00007fc236b4c93b in  () at /usr/lib/libGLX_nvidia.so.0
#9  0x00007fc236b51858 in  () at /usr/lib/libGLX_nvidia.so.0
#10 0x00007fc236b4a966 in glXCreateContextAttribsARB () at /usr/lib/libGLX_nvidia.so.0
#11 0x00007fc237a5d3b8 in  () at /usr/lib/libGLX.so.0
#12 0x00007fc23d107927 in juce::OpenGLContext::CachedImage::runJob() () at /home/robbert/.vst3/Vital.vst3/Contents/x86_64-linux/Vital.so
#13 0x00007fc23d27ca9a in juce::ThreadPool::ThreadPoolThread::run() () at /home/robbert/.vst3/Vital.vst3/Contents/x86_64-linux/Vital.so
#14 0x00007fc23ce41547 in juce::threadEntryProc(void*) [clone .lto_priv.9214] () at /home/robbert/.vst3/Vital.vst3/Contents/x86_64-linux/Vital.so
#15 0x00007fc23fcfb3e9 in start_thread () at /usr/lib/libpthread.so.0
#16 0x00007fc23fad2293 in clone () at /usr/lib/libc.so.6
```

</details>

Feel free to ignore the above if this is already a known issue, but since the plugin works fine in any other host and in beta 3 and prior, I feel like this may be related.

- Robbert

**Comment by robbert-vdh** [comment]
If I diff `ldd BitwigStudioEngineAVX2` for beta 3 and beta 4 the only libraries I see statically linked are xcb and a few other X11/Xorg related libraries. Were these giving issues before? I feel like you should be able to reasonably assume that these libraries are installed on the user's system. And since Bitwig officially only supports Ubuntu/Debian based distros anways this shouldn't be an issue since the required dependencies will be installed while installing the .deb file (but of course, I don't know what lead to statically linking these libraries in the first place haha).

**Comment by abique** [comment]
We introduced a linker script in beta 4:

```
BITWIG_AUDIO_ENGINE_ABI_1.0 {
  local:
    xkb*;
    xcb*;
    FT_*;
    X*;
    _X*;
};
```

We started to statically link because we used cairo gradient which were not available on old ubuntu.

**Comment by abique** [comment]
If you don't have one for yabridge you should have one like:
```
YABRIDGE_PLUGIN_ABI_1.0 {
  global:
    GetPluginFactory;
    ModuleEntry;
    ModuleExit;
    VSTPluginMain;
  local:
    *;
};
```

**Comment by abique** [comment]
We use dlopen with: `RTLD_NOW|RTLD_LOCAL|RTLD_DEEPBIND`.

```
       RTLD_LOCAL
              This is the converse of RTLD_GLOBAL, and the default if neither
              flag is specified.  Symbols defined in this shared  object  are
              not made available to resolve references in subsequently loaded
              shared objects.

       RTLD_DEEPBIND (since glibc 2.3.4)
              Place  the  lookup  scope  of the symbols in this shared object
              ahead of the global scope.  This means  that  a  self-contained
              object will use its own symbols in preference to global symbols
              with the same name contained in objects that have already  been
              loaded.
```

Also I think environ should be fine:
```
nm -D /home/abique/.wine/drive_c/VST/xfer/Serum_x64.so | grep "U environ"
                 U environ@@GLIBC_2.2.5
```

I will add checks that our `environ` is never null, but each time I attached the debugger, it was not null, so I'm not sure why it happens to you.

**Comment by robbert-vdh** [comment]
I had also noticed that `environ` is also not null for me when I print it directly with gdb. I'm not too familiar with this stuff, so no clue why gdb does have access to some version of `environ` while the plugin does not:

```cpp
─── Output/messages ────────────────────────────
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
VSTPluginMain (host_callback=0x539ee0) at ../src/plugin/plugin.cpp:47
47          while (wait_for_debugger) {
─── History ───────────────────────────────────
─── Breakpoints ──────────────────────────────
─── Expressions ─────────────────────────────
─── Source ─────────────────────────────────
 42  extern "C" VST_EXPORT AEffect* VSTPluginMain(
 43      audioMasterCallback host_callback) {
 44      char** actual_environ = environ;
 45  
 46      bool wait_for_debugger = true;
 47      while (wait_for_debugger) {
 48      }
 49  
 50      try {
 51          // This is the only place where we have to use manual memory management.
───────────────────────────────────────────
>>> print environ
$1 = (char **) 0x7ffe6b3f8668
>>> print actual_environ 
$2 = (char **) 0x0

```

**Comment by abique** [comment]
I've added this:

```Diff
@@ -1,3 +1,10 @@
+#ifdef PP_PLATFORM_LINUX
+# ifndef _GNU_SOURCE
+#  define _GNU_SOURCE
+# endif
+# include <unistd.h>
+#endif
+
 #include <cstdlib>
 #include <utility>
 
@@ -65,6 +72,10 @@ PluginHost::PluginHost(bool isDpiAware)
 {
    ASSERT_EQ(INSTANCE, nullptr);
 
+#ifdef PP_PLATFORM_LINUX
+   CHECKM(::environ != nullptr, "The environment variable must not be null, something is wrong.");
+#endif
+
    INSTANCE = this;
    _mainThreadId = Thread::getCurrentThreadId();
    init();
```
And it seems to fix it. I start a build I'll see if it really fixes it and if it does, it might be related to how the linker works and that it provides a dedicated environ variable, zero initalized just for you.

**Comment by robbert-vdh** [comment]
Ah, interesting. Apparently this is a known issue with `RTLD_DEEPBIND`. If you search on Google for `"RTLD_DEEPBIND" "environ" "null"`, then you'll come across quite a few bug reports that all result from this same issue. This is the oldest one I've found so far, from 2009: https://bugzilla.redhat.com/show_bug.cgi?id=480504

**Comment by abique** [comment]
Yeah, I may have got the "fix" by chance for environ, but what if there are other symbols like environ? It feels like there is no good solution.

**Comment by abique** [comment]
Interesting read: https://news.ycombinator.com/item?id=8029564

**Comment by robbert-vdh** [comment]
Yeah this looks like a tough issue to tackle. And `environ` suddenly not being broken looks very much like a side effect of defining `_GNU_SOURCE`, and other similar globals that applications would expect to be defined as part of the standard libraries may still be affected. I'm curious what's causing these issues for Vital then, because it must be something similar.

**Comment by abique** [comment]
`_GNU_SOURCE` is required to get unistd.h to define environ.
Then the check uses environ so the symbol is marked as DT_NEEDED and present in the global symbol table.
My guess..

**Comment by abique** [comment]
It did not work from the release build, so I'm trying now to remove the deep bind.

**Comment by abique** [comment]
Should be working for Bitwig 3.3 Beta 5.

**Comment by robbert-vdh** [comment]
I haven't been able to check for myself since my upgrade plan just expired, but from what I've heard everything seems to work great again in beta 5. Thanks a lot for looking into this!

**Comment by abique** [comment]
What is you bitwig account?

**Comment by robbert-vdh** [comment]
My Bitwig account is robbert-vdh/mail@robbertvanderhelm.nl.

**Comment by abique** [comment]
You can use Bitwig Beta 5 now. ;-)

**Comment by robbert-vdh** [comment]
Thanks a lot! I really appreciate it.

**Comment by abique** [comment]
We also appreciate what you do and wish that you continue doing it and keep using Bitwig if you like the software.
:beers:
